---
- name: Install Java
  yum:
    name: "{{ item }}"
    state: "{{ devtools_yum_state }}"
  with_items:
    - "{{ devtools_var_java_package_centos }}"
  tags: installpackages,java

- name: Get JAVA_HOME path.
  shell: alternatives --display java | grep current | sed 's/link currently points to //' | sed 's|/bin/java||'
  register: centosjavahome
  ignore_errors: yes
  become: true
  become_user: "{{ devtools_user }}"
  tags: java

- name: Set java home env var
  lineinfile:
    dest: /etc/environment
    line: "JAVA_HOME={{ centosjavahome.stdout|replace(' ','') }}"
    backup: no
  become: true
  tags: java

- name: Set java home env var in bashrc for {{ devtools_user }} user
  lineinfile:
    dest: /home/{{ devtools_user }}/.bashrc
    line: "JAVA_HOME={{ centosjavahome.stdout|replace(' ','') }}"
    backup: no
    insertbefore: '#THIS MUST BE AT THE END OF THE FILE'
  become: "{{ devtools_user }}"
  tags: java

- name: Set java home env var in bashrc for root user
  lineinfile:
    dest: /root/.bashrc
    line: "JAVA_HOME={{ centosjavahome.stdout|replace(' ','') }}"
    backup: no
  become: true
  tags: java

- name: Test JAVA_HOME set correctly for Centos for {{ devtools_user }} user.
  shell: source /home/{{ devtools_user }}/.bashrc && env | grep -i JAVA_HOME
  register: bashrcjavahome
  ignore_errors: yes
  become: true
  become_user: "{{ devtools_user }}"
  failed_when: (redhatjavahome.stdout.find("{{ centosjavahome.stdout|replace(' ','') }}") == -1)
  tags: java,test

- name: Test JAVA_HOME set correctly for Centos for root user.
  shell: source /root/.bashrc && env | grep -i JAVA_HOME
  ignore_errors: yes
  become: true
  failed_when: (bashrcjavahome.stdout.find("{{ centosjavahome.stdout|replace(' ','') }}") == -1)
  tags: java,test
