---
- name: ensure required packages installed
  yum:
    name: "{{ item }}"
    state: "{{ devtools_yum_state }}"
    update_cache: yes
  with_items:
    - zip
    - unzip
    - telnet
    - wget
    - curl
    - chromium
    - bind-utils
  tags: installpackages
