---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
  enabled: False
platforms:
  - name: centos
    box: mtbvang/centos7-desktop
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: False
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
