---
- name: Converge
  become: true
  remote_user: root
  hosts: 
    - all
  pre_tasks:
    - name: Gathering facts
      setup:
  roles:
    - role: ansible-role-devtools
      devtools_update_packages: yes
      devtools_user: vagrant
      devtools_password: vagrant

